---
title: "IK WHAT IM DOING BITCH SAY WAA"
author: "Irina Lerner"
date: "27/06/24"
output:
  html_document:
    toc: yes
    toc_float: yes
    theme: paper
editor_options: 
  chunk_output_type: inline
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# Include personal function file
source("functions.R")

# Set a seed for reproducibility
set.seed(123)
```

```{r data, include=FALSE}
# custom theme
custom_theme <- theme_minimal() +
                theme(text = element_text(size = 12),
                      plot.title = element_blank(),
                      panel.grid.major = element_blank(),
                      panel.grid.minor = element_blank())

# data
shp <- st_read("../data/30_full.shp")
data <- edit_shp(shp)
spatial <- data
```


```{r, echo=FALSE}
plot_EVI <- plot_map(spatial, "EVI_mean", "local EVI")
plot_SVIp <- plot_map(spatial, "SVIpn", "proximal SVI")
plot_SEVIp <- plot_map(spatial, "SEVIproximal", "proximal SEVI")
plot_SVId <- plot_map(spatial, "SVIdn", "distal SVI")
plot_SEVId <- plot_map(spatial, "SEVIdistal", "distal SEVI")
plot_CR <- plot_map(spatial, "CRn", "CR")
plot_AB <- plot_map(spatial, "ABn", "AB")
plot_pop <- plot_map(spatial, "popn", "pop")

legend_grob <- plot_dummy_legend()

# Combine the plots into a 2x2 layout
combined_plots <- grid.arrange(
  plot_CR, plot_AB, plot_pop, plot_EVI,
  plot_SVIp, plot_SEVIp, plot_SVId, plot_SEVId, 
  ncol = 4,
  top = "")

final_plot <- arrangeGrob(
                    combined_plots,
                    legend_grob,
                    ncol = 1,
                    heights = c(2, 1.3))  # Adjust the relative heights as needed

grid.arrange(final_plot)
```

```{r, echo=FALSE}
# Calculate pairwise correlations
correlations <- cor(as.data.frame(spatial)[, c("CR", "AB", "pop", "EVI_mean", "SVIproximal", "SGVIproximal", "SUVIproximal", "SEVIproximal", "SVIdistal", "SGVIdistal", "SUVIdistal", "SEVIdistal")], use = "complete.obs")

# Convert the correlation matrix to a data frame for easier export
correlation_df <- as.data.frame(correlations)

# Display the correlation data frame
correlation_df

write.csv2(correlation_df, "pairwise_correlations.csv")
```


# LOCAL MVPART

```{r, echo=FALSE}
#train_data <- as.data.frame(spatial[!is.na(spatial$AB),])#[train_indices, ]
# Randomly sample 30% of the data
#train_data <- as.data.frame(spatial) %>% sample_frac(0.1)

# Assign the sampled data to your train_data variable
train_data <- as.data.frame(spatial)#[train_indices, ]
#train_data <- train_data[]

train_data <- train_data %>%
  mutate(CRn = z_scale(train_data$CR),
         ABn = z_scale(train_data$AB),
         popn = z_scale(train_data$pop))

# Define the training datasets
X_train <- train_data %>% select(EVI_mean, SVIproximal, SVIdistal, SGVIproximal, SGVIdistal, SUVIproximal, SUVIdistal)
#X_train <- train_data %>% select(SVI, SGVI, SUVI)
Y_train <- train_data %>% select(CRn, ABn, popn)

# Combine the response variables into a matrix
response <- cbind(Y_train$CRn,  Y_train$ABn, Y_train$popn)

mvpart_model <- mvpart(response ~ ., data = X_train,
                    xv = "none", # select smallest tree within 1 se
                    #xval = nrow(response), # number of cross-validations
                    #xvmult = 10, # number of multiple cross-validations
                    size = 8,
                    which = 4,
                    legend = FALSE, margin = 0.01, cp = 0, prn = F)
```

```{r, echo=FALSE}
mvpart2_model <- mvpart(response ~ ., data = X_train,
                    xv = "none", # select smallest tree within 1 se
                    #xval = nrow(response), # number of cross-validations
                    #xvmult = 10, # number of multiple cross-validations
                    size = 8,
                    which = 4,
                    legend = FALSE, margin = 0.01, cp = 0, prn = F)
```

# DISTANCE ANALYSIS

Cross-validation

```{r}
# Define the control for cross-validation
train_control <- trainControl(method = "cv", number = 10)

# Train the model using cross-validation
cr_final <- train(CR ~ EVI_mean * SVIproximal * SUVIproximal * SVIdistal * SUVIdistal, 
                  data = na.omit(spatial[,-23]), method = "lm", trControl = train_control)

# Print the results
print(cr_final)

# Summary of the final model
summary(cr_final$finalModel)

library(dotwhisker)
library(broom)

# Create a coefficient plot
dwplot(lm(CR ~ EVI_mean * SVIproximal * SUVIproximal * SVIdistal * SUVIdistal, spatial)) +
  theme_bw() +
  labs(title = "Coefficient Plot with Interactions",
       x = "Coefficient Estimate",
       y = "")
```

```{r}
# Define the control for cross-validation
train_control <- trainControl(method = "cv", number = 10)

# Train the model using cross-validation
ab_final <- train(AB ~ EVI_mean + SVIproximal + SGVIproximal + SVIdistal + SGVIdistal, 
                  data = as.data.frame(na.omit(spatial[,-21])), method = "lm", trControl = train_control)

# Print the results
print(ab_final)

# Summary of the final model
summary(ab_final$finalModel)

# Create a coefficient plot
dwplot(lm(AB ~ EVI_mean + SVIproximal + SGVIproximal + SVIdistal + SGVIdistal, spatial)) +
  theme_bw() +
  labs(title = "Coefficient Plot with Interactions",
       x = "Coefficient Estimate",
       y = "")
```

We then simulate new landscapes to make the image

```{r, include=FALSE}

total0 <- expand.grid(EVI_mean = seq(0, 1, by = 0.01),
                      SEVIproximal = seq(-1, 1, by = 0.05),
                      SVIproximal = seq(0.1, 0.95, by = 0.1),
                      SEVIdistal = seq(-1, 1, by = 0.05),
                      SVIdistal = seq(0.1, 0.9, by = 0.1),
                      id = "SL")

total0 <- total0 %>%
    mutate(
            id = if_else(SEVIdistal == -1, "UP", "SP"),
            id = if_else(SEVIdistal == 1, "GP", id),
            id = if_else(SEVIproximal == -1, "UD", "SD"),
            id = if_else(SEVIproximal == 1, "GD", id)
    )

prov = 0.3
# vary proximal neigh
green_proximal <- expand.grid(SEVIproximal = seq(-1, 1, by = 0.005),
                              SVIproximal = seq(0, 1, by = 0.01))
green_proximal$EVI_mean <- prov
green_proximal$SVIdistal <- 0
green_proximal$SEVIdistal <- 1
green_proximal$id <- "GP"

sharing_proximal <- expand.grid(SEVIproximal = seq(-1, 1, by = 0.005),
                              SVIproximal = seq(0, 1, by = 0.01))
sharing_proximal$EVI_mean <- prov
sharing_proximal$SVIdistal <- 0.3
sharing_proximal$SEVIdistal <- 0
sharing_proximal$id <- "SP"

urb_proximal <- expand.grid(SEVIproximal = seq(-1, 1, by = 0.005),
                              SVIproximal = seq(0, 1, by = 0.01))
urb_proximal$EVI_mean <- prov
urb_proximal$SVIdistal <- 0
urb_proximal$SEVIdistal <- -1
urb_proximal$id <- "UP"

total <- rbind(green_proximal, urb_proximal, sharing_proximal)

# vary distal neigh
green_distal <- expand.grid(SEVIdistal = seq(-1, 1, by = 0.005),
                            SVIdistal = seq(0, 1, by = 0.01))
green_distal$EVI_mean <- prov
green_distal$SVIproximal <- 0
green_distal$SEVIproximal <- 1
green_distal$id <- "GD"

sharing_distal <- expand.grid(SEVIdistal = seq(-1, 1, by = 0.005),
                            SVIdistal = seq(0, 1, by = 0.01))
sharing_distal$EVI_mean <- prov
sharing_distal$SVIproximal <- 0.3
sharing_distal$SEVIproximal <- 0
sharing_distal$id <- "SD"

urb_distal <- expand.grid(SEVIdistal = seq(-1, 1, by = 0.005),
                          SVIdistal = seq(0, 1, by = 0.01))
urb_distal$EVI_mean <- prov
urb_distal$SVIproximal <- 0
urb_distal$SEVIproximal <- -1
urb_distal$id <- "UD"


total <- rbind(total, urb_distal, green_distal, sharing_distal)

total$SGVIproximal <- (1 + (1 - total$SVIproximal) * total$SEVIproximal - total$SVIproximal)/2
total$SUVIproximal <- (1 - (1 - total$SVIproximal) * total$SEVIproximal - total$SVIproximal)/2
total$SGVIdistal <- (1 + (1 - total$SVIdistal) * total$SEVIdistal - total$SVIdistal)/2
total$SUVIdistal <- (1 - (1 - total$SVIdistal) * total$SEVIdistal - total$SVIdistal)/2
total$SBVIproximal <- (total$SGVIproximal -  total$SUVIproximal)
total$SBVIdistal <- (total$SGVIdistal -  total$SUVIdistal)
total$EVI_mean = 0.3
```

We vary sharing and sparing in different radius to understand the interactions

```{r}
total$CRpred <- z_scale(predict(cr_final, newdata = total))
total$ABpred <- z_scale(predict(ab_final, newdata = total))
```

```{r, echo = F}
GL1 <- ggplot(total[total$id == "GL",]) +
          geom_smooth(aes(x = EVI_mean, y = (CRpred)), method = "loess", formula = y ~ x, color = "steelblue") +
          geom_smooth(aes(x = EVI_mean, y = (ABpred)), method = "loess", formula = y ~ x, color = "hotpink3") +
          labs(x = "EVI",
               y = "service provision",
               color = "Service") +
          #scale_color_manual(values = c("Climatic Relief" = "turquoise", "Aesthetic Beauty" = "purple")) +
          theme_bw() +
          theme(panel.grid.minor = element_blank())+
          ylim(-1, 1)

SL1 <- ggplot(total[total$id == "SL",]) +
          geom_smooth(aes(x = EVI_mean, y = (CRpred)), method = "loess", formula = y ~ x, color = "steelblue") +
          geom_smooth(aes(x = EVI_mean, y = (ABpred)), method = "loess", formula = y ~ x, color = "hotpink3") +
          labs(x = "EVI",
               y = "service provision",
               color = "Service") +
          #scale_color_manual(values = c("Climatic Relief" = "turquoise", "Aesthetic Beauty" = "purple")) +
          theme_bw() +
          theme(panel.grid.minor = element_blank())+
          ylim(-1, 1)

ML1 <- ggplot(total[total$id == "ML",]) +
          geom_smooth(aes(x = EVI_mean, y = (CRpred)), method = "loess", formula = y ~ x, color = "steelblue") +
          geom_smooth(aes(x = EVI_mean, y = (ABpred)), method = "loess", formula = y ~ x, color = "hotpink3") +
          labs(x = "EVI",
               y = "service provision",
               color = "Service") +
          #scale_color_manual(values = c("Climatic Relief" = "turquoise", "Aesthetic Beauty" = "purple")) +
          theme_bw() +
          theme(panel.grid.minor = element_blank())+
          ylim(-1, 1)

TL1 <- ggplot(total) +
          geom_smooth(aes(x = EVI_mean, y = (CRpred)), method = "loess", formula = y ~ x, color = "steelblue") +
          geom_smooth(aes(x = EVI_mean, y = (ABpred)), method = "loess", formula = y ~ x, color = "hotpink3") +
          labs(x = "EVI",
               y = "service provision",
               color = "Service") +
          #scale_color_manual(values = c("Climatic Relief" = "turquoise", "Aesthetic Beauty" = "purple")) +
          theme_bw() +
          theme(panel.grid.minor = element_blank())+
          ylim(-1, 1)
hb 
grid.arrange(
  GL1, UL1, ML1, SL1, TL1,
  ncol = 5)

```


```{r, echo = F}
GP1 <- plot_tern(total[total$id == "GP",], "CRpred")
SP1 <- plot_tern(total[total$id == "SP",], "CRpred")
UP1 <- plot_tern(total[total$id == "UP",], "CRpred")
GD1 <- plot_tern2(total[total$id == "GD",], "CRpred")
SD1 <- plot_tern2(total[total$id == "SD",], "CRpred")
UD1 <- plot_tern2(total[total$id == "UD",], "CRpred")
GP2 <- plot_tern(total[total$id == "GP",], "ABpred")
SP2 <- plot_tern(total[total$id == "SP",], "ABpred")
UP2 <- plot_tern(total[total$id == "UP",], "ABpred")
GD2 <- plot_tern2(total[total$id == "GD",], "ABpred")
SD2 <- plot_tern2(total[total$id == "SD",], "ABpred")
UD2 <- plot_tern2(total[total$id == "UD",], "ABpred")

grid.arrange(
  GD1, SD1, UD1,
  GD2, SD2, UD2,
  ncol = 3)

plot_tern(total, "ABpred")
```


```{r, echo=FALSE}
grid.arrange(
  UP1, UP2,
  SP1, SP2,
  GP1, GP2,
  ncol = 2)
```

```{r, echo=FALSE}
ggtern() +
  theme_bw() +  # Removes all grid lines, ticks, axis labels, etc.
  theme(
    #tern.panel.grid.major = element_blank(),
    #tern.panel.grid.minor = element_blank(),
    #tern.panel.background = element_blank(),
    tern.axis.text = element_blank(),
    tern.axis.title = element_blank()
  ) +
    labs(x = "SGVI", y = "SVI", z = "SUVI")

```
